language: android
jdk: oraclejdk8
os: linux
env:
  global:
    - ANDROID_TARGET=android-29
    - ANDROID_ABI=x86
    - ANDROID_TAG=default
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - extra-android-support
before_script:
  - sdkmanager "system-images;android-29;default;x86"
  - echo no | avdmanager create avd --force -n test --package "system-images;android-29;default;x86" --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.3"
  - chmod +x gradlew
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  browserstack:
    username: "justinkirk2"
    access_key:
      secure: "rkPo92v/IiPhgc+9FV/rSbOWY9RT/nrIXfg+g3Ixq4ZRSkXh0LuNb2RvZuYPD4OxYAalHe0Li3K9LqsVnSbzuaDndz0d+abRiuBdI4KgfA+Oeg4w+9m++kbdmRe32vGV1JQZ6sqxKZXY2h75WTgiOrXUowWHzGNp6B+mXq61tck0X95mfo3giwnPZfc4uZSeGa34wevq5Jr/euGPA51ZuX41LYJ7SU7k5GtOpg4rc7vkcx5ZwAvuXjO+cwWdh/1/E/JaRn/x6eTy7Rh618MuTviq1CLV2tm0DZsmoO4KRWFHZE/YwRM73EGLXuTS1MfMyEDejKVQalrXGHlgJPPB1r6trnS7BEv2rQa2UZNxtS4n3Mmj3IKCa9HBCZvFpkPbQWlF30rAcXcozLtJmXQpU8FUMfVTuYqvoI3oO005VOxMwQ6FFMHsPtrTJnBgz46Mm8TMHAO9Z8YvgoeqVvVVKGc+B93u7/0Z/1DoGN3R95lHF9nLYZNuwSg/8RLXL5bPdx6IecZ0ORlmedp33y1VTQsyzhfO2IAv2l5295E7aafvckkUx6LakKnlDRLWkuHdVyUuwipIXpNDKMBktiJOqbSoOglg/bVSF83tS/NiHdRX+lmxqJhRLMQredHO6S8zRCFC+N9Rwx4QpoS8ZJZCaHkjfdfZTQMO9YBJAZQM1bU="